### Check login
POST http://192.168.1.45:3800/login
content-type: application/json

{
    "username": "admin1",
    "password": "12345"
}

### Check GET
GET http://localhost:3800/home/list
content-type: application/json

### Delete
DELETE http://localhost:8088/cabinet/delete/8
content-type: application/json


### Check Update
PUT http://localhost:8088/cabinet/update/9
content-type: application/json

{
    "txt_number": "5",
    "image_field": "test",
    "txt_desc_en_cab": "testEng",
    "txt_desc_th_cab": "Thai",
    "status": "0"
}


### Check
POST http://localhost:3800/login
content-type: application/json

{
    "username":"admin1",
    "password":"12345"
}

### Check
GET http://localhost:3800/course/list

{
    
}